# Generated by Django 5.0.9 on 2024-09-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencies', '0003_alter_cryptocurrency_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprice',
            name='close_price',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicalprice',
            name='high_price',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicalprice',
            name='low_price',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicalprice',
            name='open_price',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='historicalprice',
            name='volume_from',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='historicalprice',
            name='volume_to',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
    ]
